version: '3'

services:
  web-dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - '5173:5173'
    environment:
      NODE_ENV: development
    volumes:
       - ./:/app
       - /app/node_modules
